language: node_js
node_js:
- '13'
services:
- docker
script:
- yarn install
deploy:
  provider: heroku
  api_key:
    secure: naJhHuGKbT2hclYsOK/iogc57UNxTF67M5KnOYkRX2WyeoYfxVCLZQnfq0RN+h3Wsu6zIEwxlikyMkHXH4niCDGOBMMBVGsHb7cBmgWezcMHkc3PqTX4D0nyY4679q3O0HbDy+eB/6xZXPfXm6xar6ygAMME62PlC18Zszh18i2bCGgL/a4uG5LqShXTRgeGhE6P8k6hkCeCj6HP5t83HHTQ/+jF78pcGgOrFzF1XVOb04Cfm6LpJKr0IeA9pQAOHmhmGmTkggRHkdYYZWrJxKd0CuvBbq1IyPFHAZWBow632pqPOWT26HXfhErAt8MyQpWnzjxln7hVMAEQPC8PeyQma9sjDBbEE3n6Q2XPpJqF8JoT46mDyJRF2BPFZR8gGdMuurtUc5JUGPphjF65Jj+i5alBdB/C/EKwTPvAlo4AIsaf6/BL2rkdwaAll15meKO3xd3tumFPzUGT6o7M1/2Se86C89nevEBQV8n33qLbz9oc5AL/k3P8JrZ8nw6rx8CtYyrNFJUITQkWzkD8DMsFdAHuwNShYEQtM/Df0OVEBY9mp6whjlGKBEXzmQ8rfVcztncEd/OYfg6Zmei8XEsOjSkeIvPIylQ8T78s9QsyNChwQeXP/f511maagERAqKSABb0D0LI5rVaK6vgsLZw7mH4rIB5KA8ZOMPxdkJw=
  app: check-eh
  on:
    repo: judicaelandria/check
  skip_cleanup: true
