language: nodejs

node_js:
  - "12"

script:
  - yarn build

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version version-number
  - export PATH="$HOME/.yarn/bin:$PAT"
cache:
  yarn: true
